# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'betterUI.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtGui import QFont
from PyQt5.QtWidgets import QDialog, QMessageBox

from gui.saveDialog import Ui_Dialog
from modules.settings_defaults import Settings


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setFont(QFont("MS Shell Dlg2",8))
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(893, 640)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(800, 640))
        # font = QtGui.QFont()
        # font.setPointSize(8)
        # font.setKerning(True)
        # MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName("centralwidget")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(360, 20, 502, 560))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_12.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.label_10 = QtWidgets.QLabel(self.layoutWidget)
        self.label_10.setMinimumSize(QtCore.QSize(500, 52))
        font = QtGui.QFont()
        font.setPointSize(32)
        font.setBold(False)
        font.setWeight(50)
        font.setKerning(True)
        self.label_10.setFont(font)
        self.label_10.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.label_10.setObjectName("label_10")
        self.verticalLayout_12.addWidget(self.label_10)
        self.lb_ImageSample = QtWidgets.QLabel(self.layoutWidget)
        self.lb_ImageSample.setMinimumSize(QtCore.QSize(500, 500))
        self.lb_ImageSample.setText("")
        self.lb_ImageSample.setAlignment(QtCore.Qt.AlignCenter)
        self.lb_ImageSample.setObjectName("lb_ImageSample")
        self.verticalLayout_12.addWidget(self.lb_ImageSample)
        self.layoutWidget1 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget1.setGeometry(QtCore.QRect(10, 0, 326, 553))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout()
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtWidgets.QLabel(self.layoutWidget1)
        self.label.setMinimumSize(QtCore.QSize(318, 25))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        font.setKerning(True)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSpacing(5)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.layoutWidget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setMinimumSize(QtCore.QSize(155, 13))
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.label_3 = QtWidgets.QLabel(self.layoutWidget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setMinimumSize(QtCore.QSize(154, 13))
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.spinBox_Res_Width = QtWidgets.QSpinBox(self.layoutWidget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinBox_Res_Width.sizePolicy().hasHeightForWidth())
        self.spinBox_Res_Width.setSizePolicy(sizePolicy)
        self.spinBox_Res_Width.setMinimumSize(QtCore.QSize(154, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setKerning(True)
        self.spinBox_Res_Width.setFont(font)
        self.spinBox_Res_Width.setSuffix("px")
        self.spinBox_Res_Width.setMaximum(10000)
        self.spinBox_Res_Width.setProperty("value", 256)
        self.spinBox_Res_Width.setObjectName("spinBox_Res_Width")
        self.horizontalLayout.addWidget(self.spinBox_Res_Width)
        self.spinBox_Res_Height = QtWidgets.QSpinBox(self.layoutWidget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinBox_Res_Height.sizePolicy().hasHeightForWidth())
        self.spinBox_Res_Height.setSizePolicy(sizePolicy)
        self.spinBox_Res_Height.setMinimumSize(QtCore.QSize(154, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setKerning(True)
        self.spinBox_Res_Height.setFont(font)
        self.spinBox_Res_Height.setSuffix("px")
        self.spinBox_Res_Height.setMaximum(10000)
        self.spinBox_Res_Height.setProperty("value", 256)
        self.spinBox_Res_Height.setObjectName("spinBox_Res_Height")
        self.horizontalLayout.addWidget(self.spinBox_Res_Height)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.verticalLayout_3.addLayout(self.verticalLayout_2)
        self.line = QtWidgets.QFrame(self.layoutWidget1)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_3.addWidget(self.line)
        self.verticalLayout_10.addLayout(self.verticalLayout_3)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_4 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_4.setMinimumSize(QtCore.QSize(277, 35))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        font.setKerning(True)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_3.addWidget(self.label_4)
        self.btn_textHelp = QtWidgets.QPushButton(self.layoutWidget1)
        self.btn_textHelp.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_textHelp.sizePolicy().hasHeightForWidth())
        self.btn_textHelp.setSizePolicy(sizePolicy)
        self.btn_textHelp.setMinimumSize(QtCore.QSize(15, 35))
        self.btn_textHelp.setMaximumSize(QtCore.QSize(35, 23))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        font.setKerning(True)
        self.btn_textHelp.setFont(font)
        self.btn_textHelp.setObjectName("btn_textHelp")
        self.horizontalLayout_3.addWidget(self.btn_textHelp)
        self.verticalLayout_4.addLayout(self.horizontalLayout_3)
        self.lineEdit = QtWidgets.QLineEdit(self.layoutWidget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit.sizePolicy().hasHeightForWidth())
        self.lineEdit.setSizePolicy(sizePolicy)
        self.lineEdit.setMinimumSize(QtCore.QSize(320, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(True)
        self.lineEdit.setFont(font)
        self.lineEdit.setObjectName("lineEdit")
        self.verticalLayout_4.addWidget(self.lineEdit)
        self.line_2 = QtWidgets.QFrame(self.layoutWidget1)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout_4.addWidget(self.line_2)
        self.verticalLayout_10.addLayout(self.verticalLayout_4)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_5 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_5.setMinimumSize(QtCore.QSize(320, 25))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        font.setKerning(True)
        self.label_5.setFont(font)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_5.addWidget(self.label_5)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.btn_Font = QtWidgets.QPushButton(self.layoutWidget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_Font.sizePolicy().hasHeightForWidth())
        self.btn_Font.setSizePolicy(sizePolicy)
        self.btn_Font.setMinimumSize(QtCore.QSize(156, 23))
        self.btn_Font.setObjectName("btn_Font")
        self.horizontalLayout_5.addWidget(self.btn_Font)
        self.btn_Font_Color = QtWidgets.QPushButton(self.layoutWidget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_Font_Color.sizePolicy().hasHeightForWidth())
        self.btn_Font_Color.setSizePolicy(sizePolicy)
        self.btn_Font_Color.setMinimumSize(QtCore.QSize(156, 23))
        self.btn_Font_Color.setObjectName("btn_Font_Color")
        self.horizontalLayout_5.addWidget(self.btn_Font_Color)
        self.verticalLayout_5.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.lineEdit_Selected_Font = QtWidgets.QLineEdit(self.layoutWidget1)
        self.lineEdit_Selected_Font.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_Selected_Font.sizePolicy().hasHeightForWidth())
        self.lineEdit_Selected_Font.setSizePolicy(sizePolicy)
        self.lineEdit_Selected_Font.setMinimumSize(QtCore.QSize(280, 20))
        self.lineEdit_Selected_Font.setObjectName("lineEdit_Selected_Font")
        self.horizontalLayout_4.addWidget(self.lineEdit_Selected_Font)
        self.btn_SelectedColor_Font = QtWidgets.QPushButton(self.layoutWidget1)
        self.btn_SelectedColor_Font.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_SelectedColor_Font.sizePolicy().hasHeightForWidth())
        self.btn_SelectedColor_Font.setSizePolicy(sizePolicy)
        self.btn_SelectedColor_Font.setMinimumSize(QtCore.QSize(32, 23))
        self.btn_SelectedColor_Font.setText("")
        self.btn_SelectedColor_Font.setObjectName("btn_SelectedColor_Font")
        self.horizontalLayout_4.addWidget(self.btn_SelectedColor_Font)
        self.verticalLayout_5.addLayout(self.horizontalLayout_4)
        self.checkBoxAntiAliasedText = QtWidgets.QCheckBox(self.layoutWidget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBoxAntiAliasedText.sizePolicy().hasHeightForWidth())
        self.checkBoxAntiAliasedText.setSizePolicy(sizePolicy)
        self.checkBoxAntiAliasedText.setMinimumSize(QtCore.QSize(320, 17))
        self.checkBoxAntiAliasedText.setObjectName("checkBoxAntiAliasedText")
        self.verticalLayout_5.addWidget(self.checkBoxAntiAliasedText)
        self.rotateText = QtWidgets.QCheckBox(self.layoutWidget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rotateText.sizePolicy().hasHeightForWidth())
        self.rotateText.setSizePolicy(sizePolicy)
        self.rotateText.setMinimumSize(QtCore.QSize(320, 17))
        self.rotateText.setObjectName("rotateText")
        self.verticalLayout_5.addWidget(self.rotateText)
        self.repositionText = QtWidgets.QCheckBox(self.layoutWidget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.repositionText.sizePolicy().hasHeightForWidth())
        self.repositionText.setSizePolicy(sizePolicy)
        self.repositionText.setMinimumSize(QtCore.QSize(320, 17))
        self.repositionText.setObjectName("repositionText")
        self.verticalLayout_5.addWidget(self.repositionText)
        self.verticalLayout_10.addLayout(self.verticalLayout_5)
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.label_6 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_6.setMinimumSize(QtCore.QSize(320, 25))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        font.setKerning(True)
        self.label_6.setFont(font)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_9.addWidget(self.label_6)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_7 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_7.setMinimumSize(QtCore.QSize(154, 19))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        font.setKerning(True)
        self.label_7.setFont(font)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_6.addWidget(self.label_7)
        self.checkBox_makeBorder = QtWidgets.QCheckBox(self.layoutWidget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBox_makeBorder.sizePolicy().hasHeightForWidth())
        self.checkBox_makeBorder.setSizePolicy(sizePolicy)
        self.checkBox_makeBorder.setMinimumSize(QtCore.QSize(154, 17))
        self.checkBox_makeBorder.setObjectName("checkBox_makeBorder")
        self.verticalLayout_6.addWidget(self.checkBox_makeBorder)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.btn_Border_Color = QtWidgets.QPushButton(self.layoutWidget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_Border_Color.sizePolicy().hasHeightForWidth())
        self.btn_Border_Color.setSizePolicy(sizePolicy)
        self.btn_Border_Color.setMinimumSize(QtCore.QSize(111, 23))
        self.btn_Border_Color.setObjectName("btn_Border_Color")
        self.horizontalLayout_6.addWidget(self.btn_Border_Color)
        self.btn_SelectedColor_Border = QtWidgets.QPushButton(self.layoutWidget1)
        self.btn_SelectedColor_Border.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_SelectedColor_Border.sizePolicy().hasHeightForWidth())
        self.btn_SelectedColor_Border.setSizePolicy(sizePolicy)
        self.btn_SelectedColor_Border.setMaximumSize(QtCore.QSize(35, 23))
        self.btn_SelectedColor_Border.setText("")
        self.btn_SelectedColor_Border.setObjectName("btn_SelectedColor_Border")
        self.horizontalLayout_6.addWidget(self.btn_SelectedColor_Border)
        self.verticalLayout_6.addLayout(self.horizontalLayout_6)
        self.label_8 = QtWidgets.QLabel(self.layoutWidget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_8.sizePolicy().hasHeightForWidth())
        self.label_8.setSizePolicy(sizePolicy)
        self.label_8.setMinimumSize(QtCore.QSize(154, 13))
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.verticalLayout_6.addWidget(self.label_8)
        self.spinBox_Border_Width = QtWidgets.QSpinBox(self.layoutWidget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinBox_Border_Width.sizePolicy().hasHeightForWidth())
        self.spinBox_Border_Width.setSizePolicy(sizePolicy)
        self.spinBox_Border_Width.setMinimumSize(QtCore.QSize(154, 22))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setKerning(True)
        self.spinBox_Border_Width.setFont(font)
        self.spinBox_Border_Width.setSuffix("")
        self.spinBox_Border_Width.setMaximum(10000)
        self.spinBox_Border_Width.setProperty("value", 4)
        self.spinBox_Border_Width.setObjectName("spinBox_Border_Width")
        self.verticalLayout_6.addWidget(self.spinBox_Border_Width)
        self.horizontalLayout_10.addLayout(self.verticalLayout_6)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_9 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_9.setMinimumSize(QtCore.QSize(154, 28))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        font.setKerning(True)
        self.label_9.setFont(font)
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.verticalLayout_7.addWidget(self.label_9)
        self.checkBox_fillText = QtWidgets.QCheckBox(self.layoutWidget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBox_fillText.sizePolicy().hasHeightForWidth())
        self.checkBox_fillText.setSizePolicy(sizePolicy)
        self.checkBox_fillText.setMinimumSize(QtCore.QSize(154, 17))
        self.checkBox_fillText.setObjectName("checkBox_fillText")
        self.verticalLayout_7.addWidget(self.checkBox_fillText)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.btn_Fill_Color = QtWidgets.QPushButton(self.layoutWidget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_Fill_Color.sizePolicy().hasHeightForWidth())
        self.btn_Fill_Color.setSizePolicy(sizePolicy)
        self.btn_Fill_Color.setMinimumSize(QtCore.QSize(111, 23))
        self.btn_Fill_Color.setObjectName("btn_Fill_Color")
        self.horizontalLayout_7.addWidget(self.btn_Fill_Color)
        self.btn_SelectedColor_Fill = QtWidgets.QPushButton(self.layoutWidget1)
        self.btn_SelectedColor_Fill.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_SelectedColor_Fill.sizePolicy().hasHeightForWidth())
        self.btn_SelectedColor_Fill.setSizePolicy(sizePolicy)
        self.btn_SelectedColor_Fill.setMinimumSize(QtCore.QSize(35, 23))
        self.btn_SelectedColor_Fill.setMaximumSize(QtCore.QSize(35, 23))
        self.btn_SelectedColor_Fill.setText("")
        self.btn_SelectedColor_Fill.setObjectName("btn_SelectedColor_Fill")
        self.horizontalLayout_7.addWidget(self.btn_SelectedColor_Fill)
        self.verticalLayout_7.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.btn_Background_Color = QtWidgets.QPushButton(self.layoutWidget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_Background_Color.sizePolicy().hasHeightForWidth())
        self.btn_Background_Color.setSizePolicy(sizePolicy)
        self.btn_Background_Color.setMinimumSize(QtCore.QSize(111, 23))
        self.btn_Background_Color.setObjectName("btn_Background_Color")
        self.horizontalLayout_9.addWidget(self.btn_Background_Color)
        self.btn_SelectedColor_Background = QtWidgets.QPushButton(self.layoutWidget1)
        self.btn_SelectedColor_Background.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_SelectedColor_Background.sizePolicy().hasHeightForWidth())
        self.btn_SelectedColor_Background.setSizePolicy(sizePolicy)
        self.btn_SelectedColor_Background.setMinimumSize(QtCore.QSize(35, 23))
        self.btn_SelectedColor_Background.setMaximumSize(QtCore.QSize(35, 23))
        self.btn_SelectedColor_Background.setText("")
        self.btn_SelectedColor_Background.setObjectName("btn_SelectedColor_Background")
        self.horizontalLayout_9.addWidget(self.btn_SelectedColor_Background)
        self.verticalLayout_7.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_10.addLayout(self.verticalLayout_7)
        self.verticalLayout_9.addLayout(self.horizontalLayout_10)
        self.line_3 = QtWidgets.QFrame(self.layoutWidget1)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.verticalLayout_9.addWidget(self.line_3)
        self.verticalLayout_10.addLayout(self.verticalLayout_9)
        self.verticalLayout_11.addLayout(self.verticalLayout_10)
        self.btnGenerateSample = QtWidgets.QPushButton(self.layoutWidget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnGenerateSample.sizePolicy().hasHeightForWidth())
        self.btnGenerateSample.setSizePolicy(sizePolicy)
        self.btnGenerateSample.setMinimumSize(QtCore.QSize(324, 33))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(True)
        self.btnGenerateSample.setFont(font)
        self.btnGenerateSample.setObjectName("btnGenerateSample")
        self.verticalLayout_11.addWidget(self.btnGenerateSample)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 893, 19))
        self.menubar.setObjectName("menubar")
        self.menuMenu = QtWidgets.QMenu(self.menubar)
        self.menuMenu.setObjectName("menuMenu")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.action_Generate = QtWidgets.QAction(MainWindow)
        self.action_Generate.setCheckable(False)
        self.action_Generate.setAutoRepeat(False)
        self.action_Generate.setObjectName("action_Generate")
        self.menuMenu.addAction(self.action_Generate)

        self.menuMenu.addSeparator()
        self.action_Generate.triggered.connect(self.generatePressed)
        self.menubar.addAction(self.menuMenu.menuAction())
        self.btn_textHelp.clicked.connect(self.showTextSeq_Help)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        self.qimages = []
        self.imageqs = []
        self.defaultSettings = Settings()
        self.defaultSettings.setDefaults()
        self.populateControls(self.defaultSettings)

    def construct_setting(self):
        res_W = self.spinBox_Res_Width.value()
        res_H = self.spinBox_Res_Height.value()
        # print('w:',res_W,'h:',res_H)
        text_seq = self.lineEdit.text()
        font = self.selectedFont
        font_col = self.selectedFontColor
        border = self.checkBox_makeBorder.isChecked()
        fill = self.checkBox_fillText.isChecked()
        border_col = self.selectedBorderColor
        fill_col = self.selectedFillColor
        bg_col = self.selectedBgColor
        # print(bg_col)
        border_w = self.spinBox_Border_Width.value()
        antiAliasedFont = self.checkBoxAntiAliasedText.isChecked()
        rotateText = self.rotateText.isChecked()
        repositionText = self.repositionText.isChecked()
        settings = Settings()
        settings.set(res_H, res_W, text_seq, font_col, font, bg_col, border, fill, border_w, border_col, fill_col,
                     antiAliasedFont, rotateText, repositionText)
        return settings

    def generatePressed(self):
        # print('SSTART')
        dialogW = QDialog()

        dialog = Ui_Dialog(self.construct_setting())
        dialog.setupUi(dialogW)
        dialogW.setModal(True)
        dialogW.exec_()
        # dialog.s

    def showSelectedColor(self, control: QtWidgets.QPushButton, color: QtGui.QColor):
        if (color.isValid()):
            qss = (f"background-color: {color.name()}")
            control.setStyleSheet(qss)

    def showTextSeq_Help(self):
        dialog = QMessageBox()
        dialog.setIcon(QMessageBox.Information)
        dialog.setWindowTitle('Ako zadať generovaný text')
        dialog.setText("Každý generovaný znak je ohraničený / /\n"
                       "Ak sa medzi lomkami nachádza jeden znak, tento znak bude aj vo výstupe na rovnakom mieste\n"
                       "Ak sa medzi lomkami nachádza napríklad /(A-Z)/ , znamená to, že na tomto mieste bude náhodné písmeno od A-Z\n"
                       "Rovnako môžme definovať náhodný znak z postupnosti znakov 0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz\n"
                       "Teda napríklad /(a-5)/, znamená náhodný znak z postupnosti abcdefghijklmnopqrstuvwxyz012345")
        dialog.exec_()

    def showSelectedFont(self, text):
        self.lineEdit_Selected_Font.setText(text)

    def populateControls(self, settings):
        """Zajtra, dorobit generovanie nahodnej pozicie tak, aby obdlznik nesiel cez okraj obrazka"""
        self.spinBox_Res_Width.setValue(self.defaultSettings.res_width)
        self.spinBox_Res_Height.setValue(self.defaultSettings.res_height)
        self.lineEdit.setText(self.defaultSettings.text_seq)
        self.selectedFont = settings.font
        self.showSelectedFont(self.selectedFont.family() + ' ' + str(self.selectedFont.pointSize()))
        self.selectedFontColor = settings.font_color
        self.showSelectedColor(self.btn_SelectedColor_Font, self.selectedFontColor)
        self.checkBox_makeBorder.setChecked(self.defaultSettings.border)
        self.checkBox_fillText.setChecked(self.defaultSettings.fill)
        self.selectedBorderColor = settings.border_color
        self.showSelectedColor(self.btn_SelectedColor_Border, self.selectedBorderColor)
        self.selectedFillColor = settings.fill_color
        self.showSelectedColor(self.btn_SelectedColor_Fill, self.selectedFillColor)
        self.selectedBgColor = settings.bg_color
        self.showSelectedColor(self.btn_SelectedColor_Background, self.selectedBgColor)
        self.spinBox_Border_Width.setValue(self.defaultSettings.border_width)
        self.checkBoxAntiAliasedText.setChecked(self.defaultSettings.antiAliasedFont)
        self.repositionText.setChecked(self.defaultSettings.repositionText)
        self.rotateText.setChecked(self.defaultSettings.rotateText)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_10.setText(_translate("MainWindow", "Vzorka"))
        self.label.setText(_translate("MainWindow", "Rozlíšenie obrázka"))
        self.label_2.setText(_translate("MainWindow", "Šírka"))
        self.label_3.setText(_translate("MainWindow", "Výška"))
        self.label_4.setText(_translate("MainWindow", "Generovaný text"))
        self.btn_textHelp.setText(_translate("MainWindow", "?"))
        self.lineEdit.setText(_translate("MainWindow", "/(A-Z)/(A-Z)/ /(0-9)/(0-9)/(0-9)/ /(A-Z)/(A-Z)"))
        self.label_5.setText(_translate("MainWindow", "Font "))
        self.btn_Font.setText(_translate("MainWindow", "Font"))
        self.btn_Font_Color.setText(_translate("MainWindow", "Farba fontu"))
        self.checkBoxAntiAliasedText.setText(_translate("MainWindow", "Text antialiasing"))
        self.rotateText.setText(_translate("MainWindow", "Náhodná rotácia textu"))
        self.repositionText.setText(_translate("MainWindow", "Náhodná pozícia textu"))
        self.label_6.setText(_translate("MainWindow", "Nastavenia"))
        self.label_7.setText(_translate("MainWindow", "Ohraničenie"))
        self.checkBox_makeBorder.setText(_translate("MainWindow", "Ohraničiť text"))
        self.btn_Border_Color.setText(_translate("MainWindow", "Farba ohraničenia"))
        self.label_8.setText(_translate("MainWindow", "Hrúbka ohraničenia"))
        self.label_9.setText(_translate("MainWindow", "Farby"))
        self.checkBox_fillText.setText(_translate("MainWindow", "Vyplniť text"))
        self.btn_Fill_Color.setText(_translate("MainWindow", "Farba výplne"))
        self.btn_Background_Color.setText(_translate("MainWindow", "Farba pozadia"))
        self.btnGenerateSample.setText(_translate("MainWindow", "Generuj vzorku"))
        self.menuMenu.setTitle(_translate("MainWindow", "Menu"))
        self.action_Generate.setText(_translate("MainWindow", "Generuj"))

    def showSample(self, sample):
        from PyQt5 import QtGui
        from PIL.ImageQt import ImageQt
        imageq = ImageQt(sample)
        qimage = QtGui.QImage(imageq)
        self.qimages.append(qimage)
        self.imageqs.append(imageq)
        qpix = QtGui.QPixmap.fromImage(qimage)
        self.lb_ImageSample.setVisible(True)
        self.lb_ImageSample.setPixmap(qpix)

    def fontDialog(self, initialFont):
        return QtWidgets.QFontDialog.getFont(initialFont)

    def colorDialog(self, initialColor):
        return QtWidgets.QColorDialog.getColor(initialColor)
